runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: <your-app-id>
  MASTER_KEY: <your-master-key>
  SERVER_URL: http://localhost:1337/parse
